### PR TITLE
Switch from howeyc/fsnotify to fsnotify/fsnotify

### PR DESCRIPTION
**Pull request by fazalmajid**
I  updated guac to use the newer fork https://github.com/fsnotify/fsnotify of https://github.com/howeyc/fsnotify. The former is a candidate for future inclusion in the Go standard library, and has support for additional platforms like Solaris.

### CODE REVIEW

**Comment by fazalmajid** [comment]
Hold off for now, I noticed in attempting to run example.go that the API changes to NewWatcher percolate to guac as well:

```
mordac ~/prom/src/github.com/fazalmajid/guac/example>go run example.go
# command-line-arguments
./example.go:21: not enough arguments in call to guac.NewWatcher
        have (context.Context, string, func() error)
        want (context.Context, string, time.Duration, func() error)
./example.go:26: watcher.Run undefined (type *guac.Watcher has no field or method Run, but does have guac.run)
```

**Comment by fazalmajid** [comment]
Nope, that error is in example.go, which wasn't updated to add the `debounceTime` parameter to `NewWatcher()`. Also it is using the guac API `Watcher.Run()` which seems to have been removed (and launching the goroutine now done as a side-effect of `NewWatcher()`

**Comment by stuartnelson3** [comment]
Sorry for the complication! this was only just a little program to help me reload code instead of having to use grunt watch :)

**Comment by fazalmajid** [comment]
OK, so I fixed example.go. It turns out fsnotify/fsnotify does not actually have Solaris support in the master branch yet, but it does in a pull request that hasn't been merged yet. I tested guac against fsnotify master merged with that PR.

I will see if the fsnotify upstream can accept their PR, and reissue a new PR with that version vendored into guac.

**Comment by fazalmajid** [comment]
Well, your utility is included by https://github.com/prometheus/alertmanager so someone else found it useful...

**Comment by stuartnelson3** [comment]
Hah that would be me, I'm the maintainer :)

**Pull request merged**
